export const APP_NAME = "Aura Capital";
export const API_VERSION = "v1";

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
} as const;

export const ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_CONFIGURATION: "INVALID_CONFIGURATION",
  UNAUTHENTICATED: "UNAUTHENTICATED",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  AUTH_EMAIL_ALREADY_EXISTS: "AUTH_EMAIL_ALREADY_EXISTS",
  LOGOUT_FAILED: "LOGOUT_FAILED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  QUIZ_ATTEMPT_NOT_FOUND: "QUIZ_ATTEMPT_NOT_FOUND",
  ATTEMPT_ALREADY_FINALIZED: "ATTEMPT_ALREADY_FINALIZED",
  INVALID_OPTION_FOR_QUESTION: "INVALID_OPTION_FOR_QUESTION",
  UNANSWERED_QUESTIONS: "UNANSWERED_QUESTIONS",
  INVALID_QUIZ_STATE: "INVALID_QUIZ_STATE",
  QUIZ_COMPLETION_REQUIRED: "QUIZ_COMPLETION_REQUIRED",
  INVALID_SESSION_STATE: "INVALID_SESSION_STATE",
  SIMULATION_NOT_ACTIVE: "SIMULATION_NOT_ACTIVE",
  ASSET_NOT_AVAILABLE: "ASSET_NOT_AVAILABLE",
  INSUFFICIENT_CASH: "INSUFFICIENT_CASH",
  INSUFFICIENT_POSITION: "INSUFFICIENT_POSITION",
  IDEMPOTENCY_CONFLICT: "IDEMPOTENCY_CONFLICT",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

// FEAT-027 Academy XP & Reward Ledger Policy Constants
// Locked Human Decisions:
// - Lesson first completion: 10 XP
// - Course first completion: 50 XP
// - Failed quiz: 0 XP
// - Repeated quiz attempt: 0 additional XP
// - Level mechanics: DEFERRED (Total XP authority only)
// - Historical automatic backfill: DEFERRED
export const ACADEMY_XP_POLICY = {
  LESSON_FIRST_COMPLETION_XP: 10,
  COURSE_FIRST_COMPLETION_XP: 50,
  FAILED_QUIZ_XP: 0,
  REPEAT_ATTEMPT_XP: 0,
} as const;

export const ACADEMY_REWARD_TYPES = {
  XP: "XP",
} as const;

export type AcademyRewardType =
  (typeof ACADEMY_REWARD_TYPES)[keyof typeof ACADEMY_REWARD_TYPES];

export const ACADEMY_SOURCE_TYPES = {
  LESSON_COMPLETION: "LESSON_COMPLETION",
  COURSE_COMPLETION: "COURSE_COMPLETION",
  QUIZ_PERFECT_SCORE: "QUIZ_PERFECT_SCORE",
  FLASHCARD_SESSION: "FLASHCARD_SESSION",
} as const;

export type AcademySourceType =
  (typeof ACADEMY_SOURCE_TYPES)[keyof typeof ACADEMY_SOURCE_TYPES];

export const ACADEMY_RESOURCE_TYPES = {
  LESSON: "LESSON",
  COURSE: "COURSE",
} as const;

export type AcademyResourceType =
  (typeof ACADEMY_RESOURCE_TYPES)[keyof typeof ACADEMY_RESOURCE_TYPES];

export const REWARD_LEDGER_STATUS = {
  PENDING: "PENDING",
  APPLIED: "APPLIED",
  REVERSED: "REVERSED",
} as const;

export type RewardLedgerStatus =
  (typeof REWARD_LEDGER_STATUS)[keyof typeof REWARD_LEDGER_STATUS];

